# SLYNET Core RPC Interfaces
# This file centralizes all `slynet-definterface` calls for the core backend.

(defn define-core-interfaces [definterface]
  # From backend.janet
  (definterface 'gray-package-name [] "Return a module name that contains the Gray stream symbols.")
  (definterface 'stream-line-column [:stream] "Return the column number at STREAM's position.")
  (definterface 'stream-flush-output [:stream] "Flush output on STREAM.")
  (definterface 'make-output-stream [:write-string] "Return a new character output stream that calls WRITE-STRING.")
  (definterface 'make-input-stream [:read-string] "Return a new character input stream that calls READ-STRING.")
  (definterface 'make-fd-stream [:fd :external-format] "Create a character stream from a file descriptor.")
  (definterface 'getpid [] "Return the process ID of the running Janet instance.")
  (definterface 'default-directory [] "Return the current default pathname-directory.")
  (definterface 'set-default-directory [:directory] "Set the current default pathname-directory.")
  (definterface 'create-repl [:opt :io-input :io-output] "Create a new REPL, optionally with I/O streams.")
  (definterface 'eval-in-context [:form :context] "Evaluate FORM in CONTEXT.")
  (definterface 'call-with-compilation-hooks [:func] "Call FUNC but intercept compiler conditions.")
  (definterface 'compile-string [:string :filename :line :column] "Compile STRING as if it appeared in a file.")
  (definterface 'compile-file [:filename :output-file :load] "Compile FILENAME to OUTPUT-FILE and load if LOAD is true.")
  (definterface 'make-lock [:name] "Create a lock with NAME.")
  (definterface 'with-lock [:lock :thunk] "Invoke (thunk) while holding LOCK.")
  (definterface 'make-thread [:name :function] "Create a new thread with NAME that runs FUNCTION with ARGS.")
  (definterface 'find-source-location [:symbol] "Return the source location of SYMBOL as (path line column) or nil.")
  (definterface 'symbol-info [:sym] "Return detailed info for SYM: type, value, docstring.")
  (definterface 'eval-for-emacs [:string :buffer-package :id] "Evaluate STRING in the context of BUFFER-PACKAGE.")
  (definterface 'system-info [] "Return basic system/environment info for diagnostics.")
  (definterface 'list-modules [] "Return a list of loaded module names.")
  (definterface 'list-directory [:path] "List files and directories at PATH. Returns array of names.")
  (definterface 'file-exists? [:path] "Return true if PATH exists and is a file.")
  (definterface 'directory-exists? [:path] "Return true if PATH exists and is a directory.")
  (definterface 'read-file [:path] "Read the contents of PATH as a string.")
  (definterface 'write-file [:path :string] "Write STRING to PATH. Returns true on success.")
  (definterface 'current-thread-id [] "Return the ID of the current thread.")
  (definterface 'thread-name [:thread] "Return the name of THREAD.")
  (definterface 'interactive-eval [:string] "Evaluate STRING interactively.")
  (definterface 'describe-symbol [:symbol-name] "Return a property list with information about SYMBOL-NAME.")
  (definterface 'arglist [:function-name] "Return the argument list of FUNCTION-NAME.")
  (definterface 'frame-locals [:index] "Return the local variables for the frame at INDEX.")
  (definterface 'source-aware-eval [:code :path :line :column] "Evaluate CODE with explicit source context metadata.")
  (definterface 'lookup-eval-source-map [:eval-id] "Return SLYNET source-map workaround metadata for EVAL-ID.")
  (definterface 'register-function-metadata [:name :arglist :doc :source] "Register callable arg/documentation metadata with explicit provenance.")
  (definterface 'function-metadata [:name] "Return callable metadata and support-class/provenance fields.")
  (definterface 'list-function-metadata [] "Return all registered callable metadata records.")
  (definterface 'record-instrumentation-event [:name :phase :payload] "Record a SLYNET wrapper instrumentation event.")
  (definterface 'list-instrumentation-events [] "Return recorded SLYNET instrumentation events.")
  (definterface 'clear-instrumentation-events [] "Clear recorded SLYNET instrumentation events.")
  (definterface 'debugger-control-capabilities [] "Return debugger control capability metadata and support status.")
  (definterface 'debugger-control-action [:operation :frame-index] "Attempt a debugger control action, returning unsupported/pending metadata when unavailable.")
  (definterface 'list-restart-scopes [] "Return current synthetic restart scopes and CL-equivalence metadata.")
  (definterface 'instrumented-eval-with-restarts [:code :requested-restart :retry-code] "Evaluate CODE in a SLYNET-owned synthetic restart scope.")
  (definterface 'invoke-synthetic-restart [:restart-name] "Invoke or report unsupported synthetic restart metadata outside an active scope.")
  (definterface 'register-execution-unit [:unit-id :name :role :path :line :column] "Register a named SLYNET execution unit with source metadata.")
  (definterface 'start-execution-unit [:name :role :source-context] "Start a managed SLYNET execution-unit record.")
  (definterface 'list-execution-units [] "Return SLYNET-managed execution units and connection units.")
  (definterface 'execution-unit-status [:unit-id] "Return the status record for UNIT-ID.")
  (definterface 'execution-unit-interrupted? [:unit-id] "Return true when UNIT-ID has observed a cooperative interruption request.")
  (definterface 'complete-execution-unit [:unit-id :status :last-output] "Complete UNIT-ID with STATUS and LAST-OUTPUT.")
  (definterface 'finish-execution-unit [:unit-id :status :last-output] "Finish UNIT-ID with STATUS and LAST-OUTPUT.")
  (definterface 'interrupt-execution-unit [:unit-id] "Request cooperative interruption for a SLYNET execution unit.")
  (definterface 'debugger-step-checkpoint [:frame-index] "Return an emulated debugger step checkpoint for FRAME-INDEX.")
  (definterface 'runtime-eval-diagnostics [:code :path :line :column] "Evaluate CODE and normalize runtime errors as Janet diagnostics.")
  (definterface 'runtime-error-diagnostics [:code :path :line :column] "Evaluate CODE and render runtime error diagnostics for Emacs.")
  (definterface 'normalize-test-failure-diagnostic [:test-name :message :path :line] "Normalize a test failure into a Janet diagnostic entry.")
  (definterface 'test-failure-diagnostic [:test-name :path :line :column :message] "Return a Janet diagnostics envelope for a test failure.")
  (definterface 'namespace-completions [:prefix :project-root :package] "Return source-index-backed Janet namespace completions.")
  (definterface 'slynet-trace-eval [:code :path :line :column] "Evaluate CODE and record a source-linked SLYNET trace/timing record.")
  (definterface 'slynet-trace-report [] "Return SLYNET wrapper trace/timing records.")
  (definterface 'slynet-clear-trace-report [] "Clear SLYNET wrapper trace/timing records.")
  (definterface 'profile [:name] "Register a SLYNET wrapper-profile record for NAME.")
  (definterface 'profile-reset [] "Clear SLYNET wrapper profile records.")
  (definterface 'profile-report [] "Return SLYNET wrapper profile records.")
  (definterface 'profile-package [:package] "Register package-level profile intent metadata.")
  (definterface 'backend-runtime-capabilities [] "Return backend runtime utility support records.")
  (definterface 'backend-runtime-operation [:operation] "Call or explain a backend runtime utility operation.")
  (definterface 'slynet-protocol-interfaces [:filter] "Browse SLYNET protocol interface registry entries.")
  (definterface 'slynet-describe-protocol-interface [:name] "Describe one SLYNET protocol interface registry entry.")
  (definterface 'slynk-compile-string [:code :buffer :position :filename :policy] "SLYNK-shaped Janet compile-string compatibility wrapper.")
  (definterface 'slynk-compile-file [:path] "SLYNK-shaped Janet compile-file compatibility wrapper.")
  (definterface 'slynet-project-snapshot [:project-root :name :metadata] "Record Janet project snapshot metadata without CL image equivalence.")
  (definterface 'slynet-record-session-event [:project-root :event-kind :payload] "Record Janet REPL/session metadata.")
  (definterface 'slynet-session-metadata [:project-root] "Return Janet project/session metadata.")
  (definterface 'namespace-browser [:project-root :package] "Return Janet namespace/module browser records.")
  (definterface 'package-local-nicknames [:package] "Return explicit unsupported CL package-local nickname metadata.")
  (definterface 'find-locally-nicknamed-package [:package :nickname] "Return explicit unsupported CL package nickname lookup metadata.")
  (definterface 'ensure-project-server-ready [:project-root :name] "Record an observable ready project server state.")
  (definterface 'project-server-status [:project-root] "Return project server lifecycle status for PROJECT-ROOT.")
  (definterface 'project-server-reconnect [:name :project-root] "Record reconnect state while preserving project identity.")
  (definterface 'project-server-note-stale [:project-root :reason] "Mark PROJECT-ROOT as stale with REASON.")
  (definterface 'slynet-trace-eval [:code :path :line :column] "Evaluate CODE and record Janet-native trace/timing metadata.")
  (definterface 'slynet-trace-report [] "Return recorded SLYNET trace/timing records.")
  (definterface 'slynet-clear-trace-report [] "Clear recorded SLYNET trace/timing records.")
  (definterface 'slynet-protocol-interfaces [:pattern] "Return SLYNET protocol interface records filtered by PATTERN.")
  (definterface 'slynet-describe-protocol-interface [:name] "Return one SLYNET protocol interface description.")
  (definterface 'slynet-project-snapshot [:project-root :name :metadata] "Record Janet-native project snapshot metadata without CL image equivalence.")
  (definterface 'slynet-record-session-event [:project-root :event-kind :payload] "Record Janet-native REPL/session metadata for PROJECT-ROOT.")
  (definterface 'slynet-session-metadata [:project-root] "Return Janet-native project session metadata.")
  (definterface 'debugger-frame-details [:frame-number] "Return structured debugger frame details.")
  (definterface 'thread-info [:thread-id] "Return SLYNET execution-unit metadata for THREAD-ID.")
  (definterface 'frame-source-location [:frame-number] "Return source location metadata for a debugger frame.")
  (definterface 'inspect-for-emacs [:value] "Inspect VALUE and return an Emacs-renderable inspector payload.")
  (definterface 'macroexpand-1-for-emacs [:form] "Macroexpand FORM once for Emacs.")
  (definterface 'macroexpand-all-for-emacs [:form] "Macroexpand FORM completely for Emacs.")
  (definterface 'macroexpand-all [:form] "Macroexpand FORM completely using Janet semantics.")

  # From contrib/slynet-apropos.janet
  (definterface 'slynet-apropos [:string-or-pattern :external-only :case-sensitive :package] "Return apropos matches for STRING-OR-PATTERN.")
  (definterface 'slynet-apropos/search-symbols [:string-or-pattern :extern-symbols :case-sensitive :limit] "Search for symbols matching the given string or pattern.")
  (definterface 'slynet-apropos/list-all-symbols [:package-name] "List all symbols in the specified package/module.")
  (definterface 'slynet-apropos/describe-symbol-for-emacs [:symbol] "Return a property list with documentation about a symbol.")

  # From contrib/slynet-indentation.janet
  (definterface 'slynet-indentation/update-indentation-rule [:symbol :spec] "Update the indentation rule for a specific symbol.")
  (definterface 'slynet-indentation/get-indentation-rule [:symbol] "Get the indentation rule for a specific symbol.")
  (definterface 'slynet-indentation/load-default-rules [] "Load the default indentation rules.")

  # From contrib/slynet-arglists.janet
  (definterface 'slynet-arglists/update-arglist [:symbol :new-arglist] "Update the argument list for a function. This can be used by editor extensions to supplement or correct arglist information.")
  (definterface 'slynet-arglists/clear-arglists-cache [] "Clear the arglist cache.")
  (definterface 'slynet-arglists/get-arglist-from-cache [:symbol] "Retrieve the cached arglist for a function, if available.")
  (definterface 'slynet-arglists/show-arglist [:symbol] "Display the arglist in the minibuffer.")

  # From docs/missing_protocol_definterface.md

  # Core SLYNK
  # slynk.lisp
  (definterface 'simple-completions [:prefix :package] "Return a list of simple completions for a given prefix and package.")
  (definterface 'apropos-list-for-emacs [:string :&optional :external-only :case-sensitive :package] "Return a list of apropos matches for a string.")
  (definterface 'ping [:tag] "A simple ping to check the connection.")
  (definterface 'connection-info [] "Return information about the current connection.")
  (definterface 'toggle-debug-on-slynk-error [] "Toggle debugging on SLYNK errors.")
  (definterface 'interactive-eval-region [:region] "Evaluate a region of code interactively.")
  (definterface 're-evaluate-defvar [:form] "Re-evaluate a defvar form.")
  (definterface 'pprint-eval [:string] "Pretty-print the evaluation of a string.")
  (definterface 'set-package [:package-name] "Set the current package.")
  (definterface 'ed-in-emacs [:what] "Edit a file or function in Emacs.")
  (definterface 'inspect-in-emacs [:what] "Inspect an object in Emacs.")
  (definterface 'value-for-editing [:form] "Get a value for editing.")
  (definterface 'commit-edited-value [:form :new-value] "Commit an edited value.")
  (definterface 'backtrace [:start :end] "Return a backtrace.")
  (definterface 'debugger-info-for-emacs [:start :end] "Return debugger information for Emacs.")
  (definterface 'invoke-nth-restart [:level :n] "Invoke the nth restart.")
  (definterface 'sly-db-abort [] "Abort the current debugger.")
  (definterface 'sly-db-continue [] "Continue from the current debugger.")
  (definterface 'throw-to-toplevel [] "Throw to the toplevel.")
  (definterface 'invoke-nth-restart-for-emacs [:level :n] "Invoke the nth restart for Emacs.")
  (definterface 'eval-string-in-frame [:string :frame-number] "Evaluate a string in a given frame.")
  (definterface 'pprint-eval-string-in-frame [:string :frame-number] "Pretty-print the evaluation of a string in a given frame.")
  (definterface 'frame-package-name [:frame-number] "Return the package name of a given frame.")
  (definterface 'frame-locals-and-catch-tags [:frame-number] "Return the locals and catch tags of a given frame.")
  (definterface 'sly-db-disassemble [:frame-number] "Disassemble a frame.")
  (definterface 'sly-db-return-from-frame [:frame-number :form] "Return from a frame.")
  (definterface 'sly-db-break [:function-name] "Set a breakpoint on a function.")
  (definterface 'sly-db-step [:frame-number] "Step the debugger.")
  (definterface 'sly-db-next [:frame-number] "Step to the next form in the debugger.")
  (definterface 'sly-db-out [:frame-number] "Step out of the current form in the debugger.")
  (definterface 'toggle-break-on-signals [:condition] "Toggle breaking on signals.")
  (definterface 'sdlb-print-condition [] "Print the current condition in the debugger.")
  (definterface 'compile-file-for-emacs [:filename :load-p :&rest :options] "Compile a file for Emacs.")
  (definterface 'compile-string-for-emacs [:string :buffer :position :filename :policy] "Compile a string for Emacs.")
  (definterface 'compile-multiple-strings-for-emacs [:strings :policy] "Compile multiple strings for Emacs.")
  (definterface 'compile-file-if-needed [:filename :load-p] "Compile a file if it is needed.")
  (definterface 'load-file [:filename] "Load a file.")
  (definterface 'slynk-require [:modules] "Require a list of SLYNK modules.")
  (definterface 'slynk-add-load-paths [:paths] "Add paths to the load path.")
  (definterface 'slynk-macroexpand-1 [:form] "Macroexpand a form once.")
  (definterface 'slynk-macroexpand [:form] "Macroexpand a form.")
  (definterface 'slynk-macroexpand-all [:form] "Macroexpand a form completely.")
  (definterface 'slynk-compiler-macroexpand-1 [:form] "Compiler-macroexpand a form once.")
  (definterface 'slynk-compiler-macroexpand [:form] "Compiler-macroexpand a form.")
  (definterface 'compiler-macroexpand-1 [:form :&optional :env] "Compiler-macroexpand a form once using Janet expansion semantics.")
  (definterface 'compiler-macroexpand [:form :&optional :env] "Repeatedly compiler-macroexpand a form using Janet expansion semantics.")
  (definterface 'slynk-expand-1 [:form] "Expand a form once.")
  (definterface 'slynk-expand [:form] "Expand a form.")
  (definterface 'slynk-format-string-expand [:format-string] "Expand a format string.")
  (definterface 'disassemble-form [:form] "Disassemble a form.")
  (definterface 'operator-arglist [:operator-name :package] "Return the arglist of an operator.")
  (definterface 'describe-function [:function-name] "Describe a function.")
  (definterface 'describe-definition-for-emacs [:name :type] "Describe a definition for Emacs.")
  (definterface 'documentation-symbol [:symbol-name] "Return the documentation for a symbol.")
  (definterface 'slynet-documentation-symbol [:symbol-name] "Return SLYNET doc-browser payload for a Janet symbol.")
  (definterface 'list-all-package-names [:&optional :nicknames] "List all package names.")
  (definterface 'slynk-toggle-trace [:spec] "Toggle tracing for a function.")
  (definterface 'untrace-all [] "Untrace all functions.")
  (definterface 'undefine-function [:symbol-name] "Undefine a function.")
  (definterface 'remove-method-by-name [:name :qualifiers :specializers] "Remove a method by name.")
  (definterface 'generic-method-specs [:name] "Return the specs of a generic method.")
  (definterface 'unintern-symbol [:symbol-name :package-name] "Unintern a symbol.")
  (definterface 'slynk-delete-package [:package-name] "Delete a package.")
  (definterface 'find-definition-for-thing [:thing] "Find the definition for a thing.")
  (definterface 'find-source-location-for-emacs [:thing] "Find the source location for a thing for Emacs.")
  (definterface 'find-definitions-for-emacs [:name] "Find definitions for a name for Emacs.")
  (definterface 'list-threads [] "List all threads.")
  (definterface 'list-execution-units [] "List SLYNET execution units.")
  (definterface 'start-execution-unit [:name :role :source-context] "Register a managed SLYNET execution unit.")
  (definterface 'finish-execution-unit [:id :status :last-output] "Finish a managed SLYNET execution unit.")
  (definterface 'execution-unit-interrupted? [:id] "Return whether a managed execution unit has a cooperative interrupt flag.")
  (definterface 'quit-thread-browser [] "Quit the thread browser.")
  (definterface 'debug-nth-thread [:n] "Debug the nth thread.")
  (definterface 'kill-nth-thread [:n] "Kill the nth thread.")
  (definterface 'start-slynk-server-in-thread [:thread-id :port-file] "Start a SLYNK server in a thread.")
  (definterface 'update-indentation-information [:info] "Update indentation information.")

  # slynk-completion.lisp
  (definterface 'flex-completions [:string :prefix :package] "Return a list of flex completions for a given prefix and package.")
  (definterface 'source-index-completion-candidates [:prefix :package] "Return source-index-backed completion candidate metadata.")

  # slynk-gray.lisp
  (definterface 'io-speed-test [:bytes-to-write] "Perform an I/O speed test.")
  (definterface 'flow-control-test [] "Perform a flow control test.")

  # xref.lisp
  (definterface 'xref [:type :symbol] "Return cross-reference information.")
  (definterface 'xrefs [:types :symbol] "Return multiple types of cross-reference information.")
  (definterface 'who-calls [:function-name] "Return static Janet call sites of a function.")
  (definterface 'who-references [:variable-name] "Return static Janet reference sites of a variable.")
  (definterface 'who-binds [:variable-name] "Return static Janet binding sites of a name.")
  (definterface 'who-sets [:variable-name] "Return static Janet set sites of a variable.")
  (definterface 'list-callers [:function-name] "Return static Janet call sites using the lower-level caller query.")

  # slynk-fancy-inspector.lisp
  (definterface 'init-inspector [:form] "Initialize the inspector.")
  (definterface 'inspector-nth-part [:n] "Return the nth part of the inspected object.")
  (definterface 'inspector-nth-part-or-lose [:n] "Return the nth part of the inspected object or lose.")
  (definterface 'inspect-nth-part [:n] "Inspect the nth part of the inspected object.")
  (definterface 'inspector-range [:from :to] "Return a range of parts of the inspected object.")
  (definterface 'inspector-call-nth-action [:n] "Call the nth action of the inspected object.")
  (definterface 'inspector-actions [] "Return SLYNET inspector action metadata for the current inspectee.")
  (definterface 'inspector-pop [] "Pop the inspector stack.")
  (definterface 'inspector-next [] "Go to the next object in the inspector history.")
  (definterface 'inspector-reinspect [] "Reinspect the current object.")
  (definterface 'inspector-toggle-verbose [] "Toggle the verbosity of the inspector.")
  (definterface 'inspector-eval [:string] "Evaluate a string in the context of the inspector.")
  (definterface 'inspector-history [] "Return the inspector history.")
  (definterface 'quit-inspector [] "Quit the inspector.")
  (definterface 'describe-inspectee [] "Describe the inspected object.")
  (definterface 'describe-inspector-part [:id] "Describe a part of the inspected object.")
  (definterface 'pprint-inspector-part [:id] "Pretty-print a part of the inspected object.")
  (definterface 'inspect-in-frame [:form :frame-number] "Inspect a form in a given frame.")
  (definterface 'inspect-current-condition [] "Inspect the current condition.")
  (definterface 'inspect-frame-var [:frame-number :var-id] "Inspect a variable in a frame.")
  (definterface 'pprint-frame-var [:frame-number :var-id] "Pretty-print a variable in a frame.")
  (definterface 'describe-frame-var [:frame-number :var-id] "Describe a variable in a frame.")
  (definterface 'eval-for-inspector [:form] "Evaluate a form for the inspector.")

  # mop.lisp
  (definterface 'mop [] "Metaobject Protocol features.")

  # Contrib
  # slynk-stickers.lisp
  (definterface 'compile-for-stickers [:form] "Compile a form for stickers.")
  (definterface 'kill-stickers [:ids] "Kill stickers.")
  (definterface 'toggle-break-on-stickers [] "Toggle breaking on stickers.")
  (definterface 'total-recordings [] "Return the total number of recordings.")
  (definterface 'search-for-recording [:query] "Search for a recording.")
  (definterface 'fetch [:id] "Fetch a recording.")
  (definterface 'forget [:id] "Forget a recording.")
  (definterface 'find-recording-or-lose [:id] "Find a recording or lose.")
  (definterface 'inspect-sticker [:id] "Inspect a sticker.")
  (definterface 'inspect-sticker-recording [:id] "Inspect a sticker recording.")

  # slynk-package-fu.lisp
  (definterface 'package= [:package1 :package2] "Check if two packages are equal.")
  (definterface 'export-symbol-for-emacs [:symbol-name :package-name] "Export a symbol for Emacs.")
  (definterface 'import-symbol-for-emacs [:symbol-name :package-name] "Import a symbol for Emacs.")
  (definterface 'unexport-symbol-for-emacs [:symbol-name :package-name] "Unexport a symbol for Emacs.")

  # sly-autodoc.el (emacs-side)
  (definterface 'autodoc [:form] "Autodoc a form.")
  (definterface 'complete-form [:form] "Complete a form.")

  # slynk-mrepl.lisp
  (definterface 'create-mrepl [] "Create an MREPL.")
  (definterface 'globally-save-object [:symbol :value] "Globally save an object.")
  (definterface 'eval-for-mrepl [:form] "Evaluate a form for MREPL.")
  (definterface 'inspect-entry [:index] "Inspect an MREPL entry.")
  (definterface 'describe-entry [:index] "Describe an MREPL entry.")
  (definterface 'pprint-entry [:index] "Pretty-print an MREPL entry.")
  (definterface 'guess-and-set-package [:string] "Guess and set the package.")
  (definterface 'copy-to-repl [:index] "Copy an MREPL entry to the REPL.")
  (definterface 'sync-package-and-default-directory [] "Sync the package and default directory.")

  # slynk-trace-dialog.lisp
  (definterface 'trace-format [:trace] "Format a trace.")
  (definterface 'trace-or-lose [:id] "Trace a part or lose.")
  (definterface 'report-partial-tree [:id] "Report a partial trace tree.")
  (definterface 'report-specs [:id] "Report trace specs.")
  (definterface 'report-total [:id] "Report total trace time.")
  (definterface 'clear-trace-tree [] "Clear the trace tree.")
  (definterface 'trace-part-or-lose [:id] "Trace a part or lose.")
  (definterface 'trace-arguments-or-lose [:id] "Trace arguments or lose.")
  (definterface 'inspect-trace-part [:id] "Inspect a trace part.")
  (definterface 'pprint-trace-part [:id] "Pretty-print a trace part.")
  (definterface 'describe-trace-part [:id] "Describe a trace part.")
  (definterface 'inspect-trace [:id] "Inspect a trace.")
  (definterface 'trace-location [:id] "Get the location of a trace.")
  (definterface 'dialog-trace [:spec] "Trace a function via dialog.")
  (definterface 'dialog-untrace [:spec] "Untrace a function via dialog.")
  (definterface 'dialog-toggle-trace [:spec] "Toggle tracing for a function via dialog.")
  (definterface 'dialog-traced-p [:spec] "Check if a function is traced via dialog.")
  (definterface 'dialog-untrace-all [] "Untrace all functions via dialog.")

  # slynk-profiler.lisp
  (definterface 'time-spec [:spec] "Time a spec.")
  (definterface 'untime-spec [:spec] "Untime a spec.")
  (definterface 'toggle-timing [:spec] "Toggle timing for a spec.")
  (definterface 'timed-spec-p [:spec] "Check if a spec is timed.")
  (definterface 'untime-all [] "Untime all specs.")
  (definterface 'report-latest-timings [] "Report the latest timings.")
  (definterface 'clear-timing-tree [] "Clear the timing tree."))

(def export-api @{:define-core-interfaces define-core-interfaces})
