(use ../mini-test)
(import ../test-tools :as tt)

(defn- plist->table [plist]
  (def out @{})
  (var i 0)
  (while (< i (length plist))
    (put out (plist i) (plist (+ i 1)))
    (set i (+ i 2)))
  out)

(defn- find-plist-by-key [items key value]
  (var found nil)
  (each item items
    (def table (plist->table item))
    (when (and (nil? found) (= value (table key)))
      (set found table)))
  found)

(deftest p25-backend-runtime-utility-capabilities {:tags [:phase25 :backend-runtime] :covers ["getpid" "create-socket" "save-image"]}
  (tt/with-test-server [srv]
    (def caps ((srv :emacs-rex!) '(backend-runtime-capabilities) :core nil 2501))
    (def getpid-cap (find-plist-by-key caps :operation :getpid))
    (def socket-cap (find-plist-by-key caps :operation :create-socket))
    (def image-cap (find-plist-by-key caps :operation :save-image))
    (assert-not-nil getpid-cap)
    (assert= :native (getpid-cap :support-class))
    (assert= true (getpid-cap :callable))
    (assert-not-nil socket-cap)
    (assert= :unsupported (socket-cap :support-class))
    (assert= false (socket-cap :callable))
    (assert= true (socket-cap :janet-runtime-extension-required))
    (assert-true (string? (socket-cap :unsupported-reason)))
    (assert-not-nil image-cap)
    (assert= :unsupported (image-cap :support-class))
    (assert= false (image-cap :cl-image-save-equivalent))
    (def op (plist->table ((srv :emacs-rex!) '(backend-runtime-operation :save-image) :core nil 2502)))
    (assert= :unsupported (op :status))
    (assert= :save-image (op :operation))
    (assert= false (op :callable))))

(deftest p26-profile-workaround-reporting {:tags [:phase26 :profile] :covers ["profile-reset" "profile" "profile-package" "profile-report"]}
  (tt/with-test-server [srv]
    ((srv :emacs-rex!) '(profile-reset) :core nil 2600)
    (def profiled (plist->table ((srv :emacs-rex!) '(profile "fixture-profile-target") :core nil 2601)))
    (assert= :profiled (profiled :status))
    (assert= :workaround (profiled :support-class))
    (assert= false (profiled :native-profiler))
    (assert= :slynet-wrapper (profiled :hook-kind))
    (def package-result (plist->table ((srv :emacs-rex!) '(profile-package "core") :core nil 2602)))
    (assert= :profile-package-registered (package-result :status))
    (assert= :workaround (package-result :support-class))
    (def report (plist->table ((srv :emacs-rex!) '(profile-report) :core nil 2603)))
    (assert= :ok (report :status))
    (assert= :workaround (report :support-class))
    (assert= false (report :native-profiler))
    (assert-true (array? (report :results)))
    (def row (find-plist-by-key (report :results) :name "fixture-profile-target"))
    (assert-not-nil row)
    (assert= :slynet-wrapper (row :hook-kind))))

(deftest p27-slynk-compile-and-macroexpand-compatibility {:tags [:phase27 :compile-load] :covers ["slynk-compile-string" "slynk-compiler-macroexpand-1" "slynk-expand"]}
  (tt/with-test-server [srv]
    (def compiled (plist->table ((srv :emacs-rex!) '(slynk-compile-string "(+ 1 2)" "p27-buffer" 1 "p27.janet") :core nil 2701)))
    (assert= true (compiled :success))
    (assert= :slynk-compile-string (compiled :operation))
    (assert= :emulated (compiled :support-class))
    (assert= false (compiled :cl-compiler-note-equivalent))
    (assert= :janet-diagnostics (compiled :diagnostic-model))
    (def expanded (plist->table ((srv :emacs-rex!) '(slynk-compiler-macroexpand-1 "(do 1)") :core nil 2702)))
    (assert= :ok (expanded :status))
    (assert= :slynk-compiler-macroexpand-1 (expanded :operation))
    (assert= :emulated (expanded :support-class))
    (assert= false (expanded :cl-compiler-macroexpand-equivalent))
    (assert-true (string? (expanded :expansion)))
    (def expand-all (plist->table ((srv :emacs-rex!) '(slynk-expand "(do 1)") :core nil 2703)))
    (assert= :ok (expand-all :status))
    (assert= :slynk-expand (expand-all :operation))
    (assert= :emulated (expand-all :support-class))))

(deftest p28-namespace-browser-and-cl-package-boundary {:tags [:phase28 :namespace] :covers ["package-local-nicknames" "find-locally-nicknamed-package"]}
  (tt/with-test-server [srv]
    (def browser (plist->table ((srv :emacs-rex!) '(namespace-browser "." "core") :core nil 2801)))
    (assert= :ok (browser :status))
    (assert= :emulated (browser :support-class))
    (assert= false (browser :cl-package-equivalent))
    (assert-true (array? (browser :namespaces)))
    (def nickname (plist->table ((srv :emacs-rex!) '(package-local-nicknames "core") :core nil 2802)))
    (assert= :unsupported (nickname :status))
    (assert= :unsupported (nickname :support-class))
    (assert= false (nickname :cl-package-local-nicknames-equivalent))
    (assert-true (string? (nickname :unsupported-reason)))
    (def lookup (plist->table ((srv :emacs-rex!) '(find-locally-nicknamed-package "core" "x") :core nil 2803)))
    (assert= :unsupported (lookup :status))
    (assert= false (lookup :cl-package-local-nicknames-equivalent))))
