# Generate a small machine-readable SLY/SLYNK-to-SLYNET protocol inventory.
# The first slice focuses on handshake/completion operations and records source,
# Janet implementation, test, and stale-doc evidence directly from repository files.

(def operations ["ping" "simple-completions" "flex-completions" "connection-info"])

(def source-files [
  "sly_source/slynk/slynk.lisp"
  "sly_source/slynk/slynk-completion.lisp"
  "sly_source/slynk/slynk-backend.lisp"
])

(def janet-files [
  "slynet/slynk.janet"
  "slynet/completion.janet"
  "slynet/interfaces.janet"
  "slynet/proto/core.janet"
  "slynet/proto/completion.janet"
])

(def test-files [
  "test/project_core_tests.janet"
  "test/server_integration_tests.janet"
  "test/channel_dispatch_tests.janet"
  "test/contrib_tests.janet"
  "test/suite-slynet.janet"
])

(def stale-doc-files [
  "docs/missing_protocol.md"
  "docs/missing_protocol_definterface.md"
])

(defn- slurp-or-empty [path]
  (try
    (slurp path)
    ([err fib] "")))

(defn- file-mentions? [path needle]
  (not (= -1 (string/find (slurp-or-empty path) needle))))

(defn- matching-files [files needle]
  (def out @[])
  (each path files
    (when (file-mentions? path needle)
      (array/push out path)))
  out)

(defn- stale-doc-state [operation]
  (if (> (length (matching-files stale-doc-files operation)) 0)
    "stale_doc_lists_as_missing"
    "not_listed_missing"))

(defn- state-for [janet-evidence test-evidence]
  (cond
    (and (> (length janet-evidence) 0)
         (> (length test-evidence) 0)) "implemented"
    (> (length janet-evidence) 0) "implemented_untested"
    true "missing"))

(defn- yaml-list [indent key values]
  (def prefix (string/repeat " " indent))
  (if (empty? values)
    (string prefix key ": []\n")
    (do
      (def out (buffer/new 0))
      (buffer/push-string out (string prefix key ":\n"))
      (each value values
        (buffer/push-string out (string prefix "  - " value "\n")))
      (string out))))

(defn- operation-record [operation]
  (def source-evidence (matching-files source-files operation))
  (def janet-evidence (matching-files janet-files operation))
  (def test-evidence (matching-files test-files operation))
  (def stale-files (matching-files stale-doc-files operation))
  (def out (buffer/new 0))
  (buffer/push-string out (string "  - name: " operation "\n"))
  (buffer/push-string out (string "    state: " (state-for janet-evidence test-evidence) "\n"))
  (buffer/push-string out (yaml-list 4 "source_files" source-evidence))
  (buffer/push-string out (yaml-list 4 "janet_files" janet-evidence))
  (buffer/push-string out (yaml-list 4 "test_files" test-evidence))
  (buffer/push-string out (string "    constraint: null\n"))
  (buffer/push-string out (string "    missing_protocol_state: " (stale-doc-state operation) "\n"))
  (buffer/push-string out (yaml-list 4 "missing_protocol_files" stale-files))
  (string out))

(defn generate-inventory []
  (os/execute ["sh" "-c" "mkdir -p docs/generated"] :p)
  (def out (buffer/new 0))
  (buffer/push-string out "# Generated by tools/protocol_inventory.janet. Do not edit by hand.\n")
  (buffer/push-string out "project: slynet\n")
  (buffer/push-string out "schema_version: 1\n")
  (buffer/push-string out "operations:\n")
  (each operation operations
    (buffer/push-string out (operation-record operation)))
  (spit "docs/generated/protocol-inventory.yml" (string out))
  true)

(generate-inventory)
