;;; slynet-project-lifecycle-tests.el --- ERT tests for SLYNET project lifecycle -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'slynet)

(ert-deftest slynet-start-project-server-waits-for-readiness ()
  (let ((started nil)
        (ready-count 0)
        (fake-process (make-symbol "fake-process")))
    (cl-letf (((symbol-function 'start-process)
               (lambda (&rest args)
                 (setq started args)
                 fake-process))
              ((symbol-function 'process-live-p)
               (lambda (process) (eq process fake-process)))
              ((symbol-function 'slynet--server-ready-p)
               (lambda (_host _port)
                 (setq ready-count (1+ ready-count))
                 (>= ready-count 2)))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _ignored) nil)))
      (let ((result (slynet-start-project-server "proj-a" :command '("janet" "slynet/cli.janet" "--tcp") :host "127.0.0.1" :port 4777)))
        (should (eq result fake-process))
        (should (equal (plist-get (gethash "proj-a" slynet-project-servers) :status) :ready))
        (should (equal (plist-get (gethash "proj-a" slynet-project-servers) :host) "127.0.0.1"))
        (should (equal (plist-get (gethash "proj-a" slynet-project-servers) :port) 4777))
        (should (eq (plist-get (gethash "proj-a" slynet-project-servers) :owned-by-emacs) t))
        (should (>= ready-count 2))
        (should (equal (car started) "slynet-proj-a"))
        (should (member "--host" started))
        (should (member "4777" started))))))

(ert-deftest slynet-reconnect-project-preserves-project-identity ()
  (let ((connection-a (slynet-client-make-test-connection nil))
        (connection-b (slynet-client-make-test-connection nil))
        (connect-count 0))
    (setf (slynet-client-connection-host connection-a) "127.0.0.1")
    (setf (slynet-client-connection-port connection-a) 4999)
    (puthash "proj-b" connection-a slynet-named-connections)
    (cl-letf (((symbol-function 'slynet-client-disconnect)
               (lambda (_connection) nil))
              ((symbol-function 'slynet-client-connect)
               (lambda (&rest args)
                 (setq connect-count (1+ connect-count))
                 (setf (slynet-client-connection-host connection-b) (plist-get args :host))
                 (setf (slynet-client-connection-port connection-b) (plist-get args :port))
                 connection-b)))
      (should (eq (slynet-reconnect-project "proj-b") connection-b))
      (should (eq (gethash "proj-b" slynet-named-connections) connection-b))
      (should (eq slynet-current-connection connection-b))
      (should (= connect-count 1))
      (should (equal (slynet-client-connection-port connection-b) 4999)))))

(ert-deftest slynet-project-server-status-renders-stale-process ()
  (let ((fake-process (make-symbol "dead-process")))
    (puthash "proj-c" (list :project "proj-c" :process fake-process :host "127.0.0.1" :port 4555 :status :ready)
             slynet-project-servers)
    (cl-letf (((symbol-function 'process-live-p)
               (lambda (_process) nil)))
      (let ((buffer (slynet-project-server-status "proj-c")))
        (with-current-buffer buffer
          (should (search-forward "proj-c" nil t))
          (should (search-forward "stale" nil t))
          (should (search-forward "127.0.0.1:4555" nil t)))))))

(ert-deftest slynet-connect-project-starts-and-owns-missing-local-server ()
  (let ((slynet-project-servers (make-hash-table :test 'equal))
        (slynet-named-connections (make-hash-table :test 'equal))
        started
        connected)
    (cl-letf (((symbol-function 'slynet-start-project-server)
               (lambda (name &rest args)
                 (setq started (cons name args))
                 (puthash name (list :project name :process 'fake :host "127.0.0.1"
                                     :port 4888 :owned-by-emacs t :status :ready)
                          slynet-project-servers)
                 'fake))
              ((symbol-function 'slynet-connect-named)
               (lambda (name &rest args)
                 (setq connected (cons name args))
                 (let ((connection (slynet-client-make-test-connection nil)))
                   (puthash name connection slynet-named-connections)
                   (setq slynet-current-connection connection)
                   connection))))
      (let ((connection (slynet-connect-project "proj-owned" :host "127.0.0.1" :port 4888)))
        (should connection)
        (should (equal (car started) "proj-owned"))
        (should (equal (car connected) "proj-owned"))
        (should (eq (plist-get (gethash "proj-owned" slynet-project-servers)
                               :owned-by-emacs)
                    t))))))

(ert-deftest slynet-disconnected-session-marks-bound-ui-buffer-stale ()
  (let* ((connection (slynet-client-make-test-connection nil))
         (slynet-current-connection connection)
         (buffer (slynet--display-buffer "*slynet-stale-test*" #'special-mode)))
    (unwind-protect
        (progn
          (slynet--handle-client-state-change connection :disconnected :connection-lost)
          (with-current-buffer buffer
            (should slynet-buffer-stale)
            (should (string-match-p "stale session" header-line-format))
            (should (string-match-p "connection-lost" header-line-format))))
      (kill-buffer buffer))))

(provide 'slynet-project-lifecycle-tests)
;;; slynet-project-lifecycle-tests.el ends here
