;;; slynet-project-lifecycle-tests.el --- ERT tests for SLYNET project lifecycle -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'slynet)

(ert-deftest slynet-start-project-server-waits-for-readiness ()
  (let ((started nil)
        (ready-count 0)
        (fake-process (make-symbol "fake-process")))
    (cl-letf (((symbol-function 'start-process)
               (lambda (&rest args)
                 (setq started args)
                 fake-process))
              ((symbol-function 'process-live-p)
               (lambda (process) (eq process fake-process)))
              ((symbol-function 'slynet--server-ready-p)
               (lambda (_host _port)
                 (setq ready-count (1+ ready-count))
                 (>= ready-count 2)))
              ((symbol-function 'accept-process-output)
               (lambda (&rest _ignored) nil)))
      (let ((result (slynet-start-project-server "proj-a" :command '("janet" "slynet/cli.janet" "--tcp") :host "127.0.0.1" :port 4777)))
        (should (eq result fake-process))
        (should (equal (plist-get (gethash "proj-a" slynet-project-servers) :status) :ready))
        (should (equal (plist-get (gethash "proj-a" slynet-project-servers) :host) "127.0.0.1"))
        (should (equal (plist-get (gethash "proj-a" slynet-project-servers) :port) 4777))
        (should (>= ready-count 2))
        (should (equal (car started) "slynet-proj-a"))))))

(ert-deftest slynet-reconnect-project-preserves-project-identity ()
  (let ((connection-a (slynet-client-make-test-connection nil))
        (connection-b (slynet-client-make-test-connection nil))
        (connect-count 0))
    (setf (slynet-client-connection-host connection-a) "127.0.0.1")
    (setf (slynet-client-connection-port connection-a) 4999)
    (puthash "proj-b" connection-a slynet-named-connections)
    (cl-letf (((symbol-function 'slynet-client-disconnect)
               (lambda (_connection) nil))
              ((symbol-function 'slynet-client-connect)
               (lambda (&rest args)
                 (setq connect-count (1+ connect-count))
                 (setf (slynet-client-connection-host connection-b) (plist-get args :host))
                 (setf (slynet-client-connection-port connection-b) (plist-get args :port))
                 connection-b)))
      (should (eq (slynet-reconnect-project "proj-b") connection-b))
      (should (eq (gethash "proj-b" slynet-named-connections) connection-b))
      (should (eq slynet-current-connection connection-b))
      (should (= connect-count 1))
      (should (equal (slynet-client-connection-port connection-b) 4999)))))

(ert-deftest slynet-project-server-status-renders-stale-process ()
  (let ((fake-process (make-symbol "dead-process")))
    (puthash "proj-c" (list :project "proj-c" :process fake-process :host "127.0.0.1" :port 4555 :status :ready)
             slynet-project-servers)
    (cl-letf (((symbol-function 'process-live-p)
               (lambda (_process) nil)))
      (let ((buffer (slynet-project-server-status "proj-c")))
        (with-current-buffer buffer
          (should (search-forward "proj-c" nil t))
          (should (search-forward "stale" nil t))
          (should (search-forward "127.0.0.1:4555" nil t)))))))

(provide 'slynet-project-lifecycle-tests)
;;; slynet-project-lifecycle-tests.el ends here
