name: CI

on:
  push:
  pull_request:

jobs:
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ['27.1', '28.2', '29.4', '30.1']
        janet_version: ['1.40.1', '1.41.1']
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Install Eldev
        run: |
          curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/eldev | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Install Janet ${{ matrix.janet_version }}
        run: |
          git clone --depth 1 --branch v${{ matrix.janet_version }} https://github.com/janet-lang/janet.git /tmp/janet
          make -C /tmp/janet -j2
          sudo make -C /tmp/janet install
      - run: make lint
      - run: make test-janet
      - run: make test-emacs
      - run: make test-e2e

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: '30.1'
      - name: Install Eldev
        run: |
          curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/eldev | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: make test-fuzz

  package:
    runs-on: ubuntu-latest
    needs: [compatibility, fuzz]
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: '30.1'
      - name: Install Eldev
        run: |
          curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/eldev | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - run: make package
      - uses: actions/upload-artifact@v4
        with:
          name: slynet-${{ github.sha }}-packages
          path: dist/
